### ISSUE TITLE
Text is not justified

### ISSUE THREAD

**Issue by pratnala** [deedy/Deedy-Resume#29]
I am curious as to why the text in this resume is not justified even though LaTeX justifies text by default. Any thoughts @deedy?

**Comment by joaosr** [comment]
You can try this @pratnala:

`\usepackage{ragged2e}`
`....`
`{\justifying \noindent Text of something.... \par}`

**Comment by pratnala** [comment]
That works @joaosr! Thanks 👍

**Comment by MaryamKhodabakhshloo** [comment]
much obliged  @joaosr :)
