### ISSUE TITLE
Cover Letters

### ISSUE THREAD

**Issue by anthonyattard** [deedy/Deedy-Resume#35]
Does anyone know of any templates that are stylistically similar to Deedy?

**Comment by wilfredom** [comment]
Yes-ish: [AwesomeCV Cover letter](https://www.sharelatex.com/templates/cover-letters/awesome-cv-cover-letter).

All instances of red can be changed to black near the beginning of the document: look for the line `\colorlet{awesome}{awesome-red}` and change `red` to `darknight`.

I also tried getting the name displayed in the same font by copying over deedy fonts and changing them in the .cls, but for some reason the last name comes out much bolder.

**Comment by anthonyattard** [comment]
Thanks for the response.

**Comment by wilfredom** [comment]
No problem! Another strategy (which I'm testing out right now) is to adapt the [single-column version](https://www.overleaf.com/latex/templates/single-column-deedy-cv-slash-resume-template/zwyxmkbrfgtz) of Deedy, by Overleaf.

**Comment by anthonyattard** [comment]
Checkout my cover letter template https://github.com/anthonyattard/Deedy-Resume

**Comment by wilfredom** [comment]
Wow, fantastic. Thanks so much, Anthony!

**Comment by anthonyattard** [comment]
Any chance this can be merged?

**Comment by anthonyattard** [comment]
PR is still open 😊 #40
