### ISSUE TITLE
Whitespace between words is removed when exporting to PDF

### ISSUE THREAD

**Issue by joshspicer** [deedy/Deedy-Resume#48]
Viewing the PDF at first glance looks fine (words appear to have  space between them). 

[Screenshot of  pdf output]

![image](https://user-images.githubusercontent.com/23246594/44477239-0d6d0d80-a608-11e8-9f66-f8e4b56eb41c.png)

When copy/pasting the text, however, this happens.
`Performednetwork,web,andoffensivepenetrationtestingforclientcompanies`

 Upon closer inspection, there actually aren't any space characters - words just have padding between them. Many companies scan in resumes, which results in them seeing this space-less version.

**Comment by StephenSchroeder** [comment]
Did you find a way to resolve this issue?
